const routes = {
    home: '/',
    cart: '/cart',
    contact: '/contact',
    customerSupport: '/customer-support',
    login: './login',
    register: './register',
    forgotPassword: './forgot-password',
    verifyCode: './verify-code',
    resetPassword: './reset-password',
    customerAccount: '/customer-account',
    promotion: '/promotion',
    newbook: '/newbook',
    admin: '/admin',
    adminCustomerAccounts: '/admin/customer-accounts',
    adminProducts: '/admin/products',
    adminCategories: '/admin/categories',
    adminOrders: '/admin/orders',
    adminVouchers: '/admin/vouchers',
    adminComplaints: '/admin/complaints',
    adminContent: '/admin/content',
    adminReports: '/admin/reports',
    adminProfile: '/admin/profile',
};

export default routes;
